version: '3'

tasks:
  default:
    desc: "List all available tasks"
    cmds:
      - task --list

  run-backend: 
    cmds:
      - cd backend && go run main.go

  run-frontend:
    cmds:
      - cd frontend && ng serve

  test-load-game-state-from-notion:
    desc: "Send a sample request to /loadGameStateFromNotion (backend must be running)"
    cmds:
      - |
        curl -X POST http://localhost:8080/api/loadGameStateFromNotion \
          -H 'Content-Type: application/json' \
          --data '{"notionUrl":"https://fabiansieper.notion.site/Notion-Quest-2c25e55239fb80f78f9df3fa2c2d65d1"}'
